import React from 'react';

import Head from 'next/head';
import { useRouter } from 'next/router';
import styled from 'styled-components';

import FirebaseAuth from '../src/modules/auth/Components/FirebaseAuth';
import useUser from '../src/modules/auth/hooks/useUser';
import styles from '../styles/Home.module.css';

const Title = styled.h1`
  color: red;
`;

function Home() {
  const { user } = useUser();
  const { replace } = useRouter();

  if (user) {
    replace('/dashboard');
    return <></>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title>Tabletop RPG</Title>

        <FirebaseAuth />
      </main>
    </div>
  );
}

export default Home;
